# Generated by Django 5.0 on 2023-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenuitems',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
