# Generated by Django 5.0 on 2023-12-11 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number should be in format: +380xxxxxxxxx', regex='^\\+?\\d{7,12}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=500)),
                ('is_precessed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
